name: Test Action
on: [push]
jobs:
  Nihao:
    runs-on: self-hosted
    steps:
      - run: echo "===== 114514 ====="
      - name: Checkout
        uses: actions/checkout@v4
      - run: bash "./test.sh"

      - name: 'Restart linux'
        run: setsid sh -c 'ansible-playbook playbook.yml -i hosts' 
