name: Test Action
on: [push]
jobs:
  Nihao:
    runs-on: [Linux]
    steps:
      - run: echo "===== 114514 ====="
      - name: Checkout
        uses: actions/checkout@v4
      - run: bash "./test.sh"

      - name: 'create ansible config'
        shell: bash
        run: |
          echo -e '[default]\nhost_key_checking = False' > ansible.cfg

      - name: 'Restart linux'
        run: |
          export PATH=$PATH:/usr/local/py3.11/bin
          setsid sh -c 'ansible-playbook playbook.yml -i hosts -b' 
