name: Test Action
on: [push]
jobs:
  Nihao:
    runs-on: ubuntu-latest
    steps:
      - run: echo "===== 114514 ====="
      - name: Checkout
        uses: actions/checkout@v4
      - run: bash pwd
      - run: bash "./test.sh"
