name: Test Action
on:
  schedule:
    - cron: '* * * * *'

jobs:
  Nihao:
    runs-on: ubuntu-latest
    steps:
      - run: echo "===== 114514 ====="
      - name: Checkout
        uses: actions/checkout@v4
      - run: bash "~/test.sh"
