name: Test Action
on: 
  push:
  workflow_dispatch:
jobs:
  bot:
    runs-on: ['self-hosted','Linux']
    steps:
      - run: echo "===== 114514 ====="
      - name: Checkout
        uses: actions/checkout@v4
      - run: bash "./test.sh"
