name: Test Action
on:
  schedule:
    - cron: '* * * * *'

jobs:
  Nihao:
    runs-on: ubuntu-latest
    steps:
      - run: echo "===== 114514 ====="
        uses: actions/checkout@v4
      - run: bash '~/test.sh'
